name: Docker Image Update

on:
  push:
    branches: [main]
    paths:
      - 'unified monitor/**'
      - '.github/workflows/docker-image-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'unified monitor/**'
      - '.github/workflows/docker-image-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: yjani204/unified-monitoring

    steps:
      - uses: actions/checkout@v4

      # 1️⃣ Authenticate to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2️⃣ Build and push the image
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: 'unified monitor'
          file:   'unified monitor/Dockerfile'
          push:   true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ github.sha }}
            ${{ env.IMAGE_REPO }}:latest
